<#
    Configuration for the Buzz API sample.

    Uses a PowerShell data file (buzz-config.psd1) — the platform-standard config
    format — loaded with the built-in Import-PowerShellDataFile (data-only, safe).

    The file lives in the project root (next to this module).
#>

Set-StrictMode -Version Latest

$script:ConfigFields = @('ServerUrl', 'ContactInformation', 'ApplicationInformation',
    'OAuthUserId', 'OAuthKid', 'PrivateKeyPath')
$script:RequiredFields = @('ServerUrl', 'OAuthUserId', 'OAuthKid', 'PrivateKeyPath')

function Get-BuzzConfigPath {
    return (Join-Path $PSScriptRoot 'buzz-config.psd1')
}

function Import-BuzzConfig {
    [CmdletBinding()]
    param([string]$Path = (Get-BuzzConfigPath))

    if (-not (Test-Path -LiteralPath $Path)) {
        [Console]::Error.WriteLine("Configuration not found (buzz-config.psd1).")
        [Console]::Error.WriteLine("  Run setup:  .\scripts\Run-BuzzSample.ps1")
        [Console]::Error.WriteLine("  or copy buzz-config.example.psd1 to buzz-config.psd1 and fill it in (see README.md).")
        exit 1
    }
    $data = Import-PowerShellDataFile -LiteralPath $Path

    $missing = @()
    foreach ($f in $script:RequiredFields) {
        if (-not $data.ContainsKey($f) -or [string]::IsNullOrEmpty([string]$data[$f])) { $missing += $f }
    }
    if ($missing.Count -gt 0) {
        [Console]::Error.WriteLine("Missing required configuration: $($missing -join ', ')")
        exit 1
    }

    $obj = [ordered]@{}
    foreach ($f in $script:ConfigFields) {
        $obj[$f] = if ($data.ContainsKey($f)) { [string]$data[$f] } else { '' }
    }
    return [pscustomobject]$obj
}

function Export-BuzzConfig {
    [CmdletBinding()]
    param([Parameter(Mandatory)][hashtable]$Config, [string]$Path = (Get-BuzzConfigPath))

    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('# Buzz API sample configuration - generated by setup.  Do not commit this file.')
    [void]$sb.AppendLine('@{')
    foreach ($f in $script:ConfigFields) {
        $val = [string]$Config[$f]
        $escaped = $val.Replace("'", "''")   # single-quote escaping for a PS single-quoted string
        [void]$sb.AppendLine(("    {0} = '{1}'" -f $f, $escaped))
    }
    [void]$sb.AppendLine('}')
    Set-Content -LiteralPath $Path -Value $sb.ToString() -Encoding Ascii
    return $Path
}

function Test-BuzzConfigComplete {
    param([string]$Path = (Get-BuzzConfigPath))
    if (-not (Test-Path -LiteralPath $Path)) { return $false }
    $data = Import-PowerShellDataFile -LiteralPath $Path
    foreach ($f in $script:RequiredFields) {
        if (-not $data.ContainsKey($f) -or [string]::IsNullOrEmpty([string]$data[$f])) { return $false }
    }
    return (Test-Path -LiteralPath ([string]$data['PrivateKeyPath']))
}

Export-ModuleMember -Function Get-BuzzConfigPath, Import-BuzzConfig, Export-BuzzConfig, Test-BuzzConfigComplete
